const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const path = require('node:path');
(async()=>{
 const browser=await chromium.launch({args:['--enable-unsafe-swiftshader']});
 const context=await browser.newContext({viewport:{width:390,height:844},acceptDownloads:true});
 const page=await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://localhost:3000');
 await page.locator('#nav-btn-games').click();
 await page.locator('#card-play-scene').click({timeout:5000});
 await page.locator('#scene-file').setInputFiles(path.join(__dirname,'fixtures/dog.jpg'));
 await page.waitForFunction(()=>document.querySelectorAll('.scene-chip').length>0,{},{timeout:120000});
 const labels=await page.locator('.scene-chip').allTextContents();
 console.log('REAL INFERENCE',labels);
 assert.ok(labels.some(x=>x.includes('dog')));
 await page.locator('.scene-chip').filter({hasText:'dog'}).first().click();
 await page.locator('#scene-save').click();
 assert.match(await page.locator('#scene-saved').innerText(),/dog/);
 await page.locator('#scene-story').click();
 assert.match(await page.locator('#scene-story-text').innerText(),/dog/);
 await page.locator('#scene-delete-photo').click();
 assert.equal(await page.locator('#scene-canvas').getAttribute('hidden'),'');
 await page.locator('#scene-file').setInputFiles({name:'bad.jpg',mimeType:'image/jpeg',buffer:Buffer.from('bad')});
 await page.waitForFunction(()=>document.querySelector('#scene-status').textContent.includes('No se pudo leer'));
 await page.locator('#scene-offline').click();
 await page.waitForFunction(()=>document.querySelector('#scene-status').textContent.includes('Offline listo'),{},{timeout:120000});
 await page.reload(); await page.locator('#nav-btn-games').click(); await page.locator('#card-play-scene').click();
 assert.match(await page.locator('#scene-saved').innerText(),/dog/);
 const stored=await page.evaluate(()=>localStorage.getItem('lingoquest_player_state_v3'));
 assert.ok(!stored.includes('data:image')); assert.ok(!stored.includes('blob:'));
 await context.setOffline(true);
 await page.reload(); await page.locator('#nav-btn-games').click(); await page.locator('#card-play-scene').click();
 await page.locator('#scene-file').setInputFiles(path.join(__dirname,'fixtures/dog.jpg'));
 await page.waitForFunction(()=>document.querySelectorAll('.scene-chip').length>0,{},{timeout:120000});
 assert.match(await page.locator('#scene-chips').innerText(),/dog/);
 console.log('OFFLINE RELOAD + REAL INFERENCE OK');
 await page.screenshot({path:'tests/scene-mobile.png',fullPage:true});
 await page.locator('#scene-close').click(); await page.locator('#nav-btn-review').click();
 await page.locator('[data-category="Scene Words"]').click();
 assert.match(await page.locator('#vocab-preview-list').innerText(),/dog/);
 await page.locator('#btn-start-srs-session').click();
 assert.match(await page.locator('.fc-word').innerText(),/dog/);
 await page.locator('#btn-fc-easy').click();
 const state=await page.evaluate(()=>JSON.parse(localStorage.getItem('lingoquest_player_state_v3')));
 assert.equal(state.cardReviews['scene-dog'].correct,1);
 assert.deepEqual(errors,[]);
 console.log('PASS mobile chips/save/story/delete/error/persistence/repaso/offline; page errors=0');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
